from typing import Dict, Any, Optional
import json

from research_agent.inno.types import Agent

# 레지스트리 API만 사용: 에이전트 등록/조회, 툴 일괄 조회
from research_agent.inno.registry import (
    register_agent,
    get_tools,
    get_agent_factory,
)  # ← 추가
from research_agent.inno.environment.docker_env import DockerEnv
from research_agent.inno.environment.docker_env import with_env as with_env_docker
from research_agent.inno.environment.markdown_browser import RequestsMarkdownBrowser


RESPONSE_REVIEW_CRITERIA = {
    "accuracy": "The factual correctness and accuracy of the response",
    "completeness": "Whether all requirements from the task are addressed",
    "consistency": "Consistency across multiple agent responses",
    "clarity": "Clarity and readability of the explanation",
    "innovation": "Presence of innovative ideas or approaches",
}


def case_resolved(
    context_variables,
    fully_correct: bool,
    review_type: str = "code_review",
    code_review_result: Optional[Dict[str, Any]] = None,
    response_review_result: Optional[Dict[str, Any]] = None,
    suggestion: Optional[Dict[str, str]] = None,
):
    """
    Use this function when you have finished the task and want to give a suggestion.
    You can only use this function after you have checked the implementation and/or responses.

    Args:
       fully_correct: whether the implementation/response is fully correct. If not, provide suggestions.
       review_type: type of review performed - "code_review", "response_review", or "both"
       code_review_result: the result of code review (required if review_type is "code_review" or "both")
       response_review_result: the result of response review (required if review_type is "response_review" or "both")
       suggestion: dict {key_point: suggestion}. If fully_correct, set to None.
    """
    suggestion_dict = {
        "review_type": review_type,
        "fully_correct": fully_correct,
    }

    if review_type in ("code_review", "both"):
        suggestion_dict["code_review"] = code_review_result
    if review_type in ("response_review", "both"):
        suggestion_dict["response_review"] = response_review_result
    if suggestion:
        suggestion_dict["suggestion"] = suggestion

    context_variables["suggestion_dict"] = suggestion_dict
    ret_val = f"""\
Here is the suggestion about the review:
Review type: {review_type}
Whether the result is fully correct: {fully_correct}
The suggestion about the review:
{json.dumps(suggestion_dict, indent=4)}
"""
    return ret_val


# 전역 레지스트리에 'get_code_review_agent' 팩토리로 등록
@register_agent("get_code_review_agent")
def get_code_review_agent(model: str, **kwargs):
    code_env: DockerEnv = kwargs.get("code_env", None)

    def instructions(context_variables):
        working_dir = context_variables.get("working_dir", None)
        return f"""You are a code reviewer, who can help me review the code in the directory: `/{working_dir}`.

      A `Machine Learning Agent` has implemented the code in the directory `/{working_dir}/project` with the innovative ideas, and you should review the code to ensure it meets the requirements of the innovative ideas, rather than a toy implementation.

      You can also review the reference codebases in the directory `/{working_dir}` to get more information about the task.

      Use `terminal_page_down` `terminal_page_up` and `terminal_page_to` to scroll the terminal output when it is too long.
      [Note] You can use `terminal_page_to` to move the viewport to the end of terminal when the middle of terminal output are meaningless, like the output of progress bar or output of generating directory structure when there are many datasets in the directory, you can use this function to move the viewport to the end of terminal where the meaningful content is.

      After reviewing the code, you should use the function `transfer_to_judge_agent` to transfer the conversation to the `Judge Agent`, and give a code review report.
      """

    # 레지스트리에서 이름 기반으로 도구 조회 + env가 필요한 툴만 자동 주입
    tool_names = [
        "read_file",
        "gen_code_tree_structure",
        "terminal_page_down",
        "terminal_page_up",
        "terminal_page_to",
    ]
    tools = get_tools(tool_names, env=code_env, env_wrapper=with_env_docker)

    return Agent(
        name="Code Review Agent",
        model=model,
        instructions=instructions,
        functions=tools,
        tool_choice="required",
    )


@register_agent("get_response_review_agent")
def get_response_review_agent(model: str, **kwargs):
    judge_agent_ref = kwargs.get("judge_agent", None)

    def instructions(context_variables):
        working_dir = context_variables.get("working_dir", None)
        return f"""You are a response reviewer, who can help me review the responses generated by agents in the directory: `/{working_dir}`.

      The agents have completed the task in the directory `/{working_dir}/project`, and you should review their responses to ensure they meet the requirements.

      Review the responses based on the following criteria:
      1. Accuracy: The factual correctness and accuracy of the response
      2. Completeness: Whether all requirements from the task are addressed
      3. Consistency: Consistency across multiple agent responses
      4. Clarity: Clarity and readability of the explanation
      5. Innovation: Presence of innovative ideas or approaches

      After reviewing the responses, you should use the function `transfer_to_judge_agent` to transfer the conversation to the `Judge Agent`, and give a response review report.
      """

    def transfer_to_judge_agent(task_report):
        """
        Transfer the conversation to the `Judge Agent`. Use this function when you want to give a report about the response review.

        Args:
           task_report: the report about the response review.
        """
        if judge_agent_ref:
            return judge_agent_ref
        return None

    response_review_agent = Agent(
        name="Response Review Agent",
        model=model,
        instructions=instructions,
        functions=[transfer_to_judge_agent],
        tool_choice="required",
    )

    return response_review_agent


@register_agent("get_judge_agent")
def get_judge_agent(model: str, **kwargs):
    file_env: RequestsMarkdownBrowser = kwargs.get("file_env", None)
    code_env: DockerEnv = kwargs.get("code_env", None)

    code_review_agent = get_code_review_agent(model, code_env=code_env)

    def instructions(context_variables):
        working_dir = context_variables.get("working_dir", None)
        return f"""You are a advisor that can help the `Machine Learning Agent` to implement the task.

      A `Machine Learning Agent` has implemented the code in the directory `/{working_dir}/project` with the innovative ideas, but I am not sure if the implementation is correct and meets the requirements of the innovative ideas, especially some specific academic definitions.

      Your job is to go through the implementation, go through the reference codebases in the directory `/{working_dir}`, and make sure the implementation is correct and meets the requirements of the innovative ideas, especially some specific academic definitions. 

      [IMPORTANT] You should carefully check whether the `Machine Learning Agent` has implemented the specific atomic idea correctly one by one based on the survey notes and the innovative idea.

      After carefully checking the implementation and the reference codebases, you should use the function `case_resolved` to propose a final suggestion about the implementation.

      You can also use `transfer_to_code_review_agent`, `transfer_to_response_review_agent`, or `transfer_to_both_reviews` to perform specific reviews.
      """

    def transfer_to_code_review_agent(atomic_idea):
        """
        Transfer the conversation to the `Code Review Agent`. Use this function when you want to review the code in the working directory.

        Args:
           atomic_idea: the atomic idea you separate from the innovative idea and the survey notes. It should be as specific and accurate as possible.
        """
        return code_review_agent

    def transfer_to_response_review_agent():
        """
        Transfer the conversation to the `Response Review Agent`. Use this function when you want to review the responses generated by agents.
        """
        return get_response_review_agent(model, judge_agent=judge_agent)

    def transfer_to_both_reviews(atomic_idea):
        """
        Transfer the conversation to perform both Code Review and Response Review. Use this function when you want to review both the code and the responses.

        Args:
           atomic_idea: the atomic idea you separate from the innovative idea and the survey notes. It should be as specific and accurate as possible.
        """
        return code_review_agent

    judge_agent = Agent(
        name="Judge Agent",
        model=model,
        instructions=instructions,
        functions=[
            case_resolved,
            transfer_to_code_review_agent,
            transfer_to_response_review_agent,
            transfer_to_both_reviews,
        ],
        tool_choice="required",
    )

    def transfer_to_judge_agent(task_report):
        """
        Transfer the conversation to the `Judge Agent`. Use this function when you want to give a report about the search, file reading, and code reviewing.

        Args:
           task_report: the report about the search, file reading, and code reviewing.
        """
        return judge_agent

    code_review_agent.functions.append(transfer_to_judge_agent)
    return judge_agent
